name = "MonteCarloIntegration"
uuid = "4886b29c-78c9-11e9-0a6e-41e1f4161f7b"
authors = ["Ranjan Anantharaman <ranjan.anantharaman@gmail.com>"]
version = "0.2.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.23, 0.24, 0.25"
QuasiMonteCarlo = "0.3"
julia = "1.6"

[extras]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HCubature", "Test"]
